name: Deploy GuardBot

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -euxo pipefail
            cd GuardBot
            
            eval \"\$(ssh-agent -s)\"
            ssh-add ~/.ssh/github_actions_deploy
          
            git pull origin master

            docker compose --project-name guard-bot down
            docker compose --project-name guard-bot up -d --build
          "
